export const HOTEL_SEARCH_REQUEST = 'HOTEL_SEARCH_REQUEST'
export const HOTEL_SEARCH_SUCCESS = 'HOTEL_SEARCH_SUCCESS'
export const HOTEL_SEARCH_FAILURE = 'HOTEL_SEARCH_FAILURE'

export const HOTEL_DETAIL_REQUEST = 'HOTEL_DETAIL_REQUEST'
export const HOTEL_DETAIL_SUCCESS = 'HOTEL_DETAIL_SUCCESS'
export const HOTEL_DETAIL_FAILURE = 'HOTEL_DETAIL_FAILURE'
export const HOTEL_DETAIL_RESET = 'HOTEL_DETAIL_RESET'

