export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST'
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
export const BOOKING_CREATE_FAILURE = 'BOOKING_CREATE_FAILURE'

export const BOOKING_FETCH_REQUEST = 'BOOKING_FETCH_REQUEST'
export const BOOKING_FETCH_SUCCESS = 'BOOKING_FETCH_SUCCESS'
export const BOOKING_FETCH_FAILURE = 'BOOKING_FETCH_FAILURE'

export const BOOKING_RESET = 'BOOKING_RESET'
