export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST'
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
export const BOOKING_CREATE_FAILURE = 'BOOKING_CREATE_FAILURE'

export const BOOKING_FETCH_REQUEST = 'BOOKING_FETCH_REQUEST'
export const BOOKING_FETCH_SUCCESS = 'BOOKING_FETCH_SUCCESS'
export const BOOKING_FETCH_FAILURE = 'BOOKING_FETCH_FAILURE'

export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST'
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS'
export const BOOKING_LIST_FAILURE = 'BOOKING_LIST_FAILURE'

export const BOOKING_CANCEL_REQUEST = 'BOOKING_CANCEL_REQUEST'
export const BOOKING_CANCEL_SUCCESS = 'BOOKING_CANCEL_SUCCESS'
export const BOOKING_CANCEL_FAILURE = 'BOOKING_CANCEL_FAILURE'

export const BOOKING_RESET = 'BOOKING_RESET'
