import type { HotelDetail } from '../../types'

export const mockHotelDetails: Record<string, HotelDetail> = {
  h1: {
    id: 'h1',
    name: 'Grand Palace Hotel',
    city: 'Mumbai',
    address: 'Marine Drive, Nariman Point, Mumbai 400021',
    starRating: 5,
    description:
      'A luxurious 5-star landmark overlooking the Arabian Sea. Grand Palace Hotel blends timeless elegance with modern comfort, featuring world-class dining, a rooftop infinity pool, and an award-winning spa for a truly indulgent stay.',
    amenities: [
      'Free high-speed Wi-Fi',
      'Rooftop infinity pool',
      'Full-service spa & wellness',
      '24x7 concierge',
      'Multi-cuisine restaurant',
      'Airport shuttle',
      'Fitness center',
      'Valet parking',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80',
      'https://images.unsplash.com/photo-1551776235-dde6d4829808?w=900&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&q=80',
    ],
    availableFrom: '2026-06-01',
    availableTo: '2026-06-30',
    rooms: [
      {
        id: 'h1-r1',
        roomType: 'Deluxe Sea View',
        description: 'Spacious room with private balcony and panoramic sea views.',
        pricePerNight: 8500,
        maxOccupancy: 2,
        bedConfig: '1 King Bed',
        imageUrl: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&q=80',
        amenities: ['Sea view', 'Smart TV', 'Mini bar', 'Rain shower'],
        availableCount: 4,
      },
      {
        id: 'h1-r2',
        roomType: 'Executive Suite',
        description: 'Two-room suite with lounge, work area, and butler service.',
        pricePerNight: 14500,
        maxOccupancy: 3,
        bedConfig: '1 King Bed + Sofa',
        imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
        amenities: ['Lounge access', 'Butler service', 'Bathtub', 'Nespresso machine'],
        availableCount: 2,
      },
    ],
  },
  h2: {
    id: 'h2',
    name: 'City Comfort Inn',
    city: 'Mumbai',
    address: 'Linking Road, Bandra West, Mumbai 400050',
    starRating: 3,
    description:
      'A comfortable mid-range hotel in the heart of Bandra, perfect for business and leisure travelers. Modern rooms, friendly staff, and excellent connectivity to the city.',
    amenities: [
      'Free Wi-Fi',
      'Complimentary breakfast',
      'Business center',
      '24x7 front desk',
      'Laundry service',
      'Parking',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80',
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=900&q=80',
    ],
    availableFrom: '2026-06-05',
    availableTo: '2026-06-20',
    rooms: [
      {
        id: 'h2-r1',
        roomType: 'Standard Double',
        description: 'Cozy room with all essentials for a comfortable stay.',
        pricePerNight: 3200,
        maxOccupancy: 2,
        bedConfig: '1 Queen Bed',
        imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
        amenities: ['Air conditioning', 'TV', 'Work desk'],
        availableCount: 6,
      },
      {
        id: 'h2-r2',
        roomType: 'Family Room',
        description: 'Larger room suitable for small families.',
        pricePerNight: 4800,
        maxOccupancy: 4,
        bedConfig: '1 Queen + 2 Single',
        imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
        amenities: ['Family-friendly', 'Mini fridge', 'Extra storage'],
        availableCount: 3,
      },
    ],
  },
  h3: {
    id: 'h3',
    name: 'The Royal Orchid',
    city: 'Delhi',
    address: 'Connaught Place, New Delhi 110001',
    starRating: 4,
    description:
      'Elegant 4-star hotel located in the heart of Delhi. Enjoy refined dining, modern amenities, and easy access to top attractions and shopping.',
    amenities: [
      'Free Wi-Fi',
      'Outdoor pool',
      'Spa services',
      'Multi-cuisine restaurant',
      'Conference rooms',
      'Airport transfer',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80',
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=900&q=80',
    ],
    availableFrom: '2026-06-08',
    availableTo: '2026-06-25',
    rooms: [
      {
        id: 'h3-r1',
        roomType: 'Premium Room',
        description: 'Modern room with city skyline view.',
        pricePerNight: 5800,
        maxOccupancy: 2,
        bedConfig: '1 King Bed',
        imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
        amenities: ['City view', 'Smart TV', 'Tea/Coffee maker'],
        availableCount: 5,
      },
      {
        id: 'h3-r2',
        roomType: 'Junior Suite',
        description: 'Comfortable suite with sitting area and city view.',
        pricePerNight: 9200,
        maxOccupancy: 3,
        bedConfig: '1 King + Sofa',
        imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80',
        amenities: ['Lounge', 'Bathtub', 'Premium toiletries'],
        availableCount: 2,
      },
    ],
  },
  h4: {
    id: 'h4',
    name: 'Seaside Resort',
    city: 'Goa',
    address: 'Calangute Beach Road, North Goa 403516',
    starRating: 4,
    description:
      'A beachfront resort that captures the laid-back spirit of Goa. Wake up to the sound of waves, lounge by the pool, and savor fresh seafood at our beachside restaurant.',
    amenities: [
      'Private beach access',
      'Outdoor pool',
      'Beach bar',
      'Free Wi-Fi',
      'Bicycle rentals',
      'Spa & yoga deck',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=900&q=80',
    ],
    availableFrom: '2026-06-10',
    availableTo: '2026-06-15',
    rooms: [
      {
        id: 'h4-r1',
        roomType: 'Garden Cottage',
        description: 'Private cottage surrounded by tropical greenery.',
        pricePerNight: 6500,
        maxOccupancy: 2,
        bedConfig: '1 Queen Bed',
        imageUrl: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800&q=80',
        amenities: ['Garden view', 'Outdoor seating', 'AC'],
        availableCount: 4,
      },
      {
        id: 'h4-r2',
        roomType: 'Beachfront Villa',
        description: 'Spacious villa with direct beach access and plunge pool.',
        pricePerNight: 12500,
        maxOccupancy: 4,
        bedConfig: '2 Queen Beds',
        imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
        amenities: ['Plunge pool', 'Beach view', 'Living area', 'Butler service'],
        availableCount: 1,
      },
    ],
  },
  h5: {
    id: 'h5',
    name: 'Budget Stay Express',
    city: 'Delhi',
    address: 'Karol Bagh, Central Delhi 110005',
    starRating: 2,
    description:
      'Clean, comfortable, and budget-friendly accommodation in central Delhi. Perfect for short stays and travelers on the go.',
    amenities: [
      'Free Wi-Fi',
      '24x7 reception',
      'Daily housekeeping',
      'Luggage storage',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=80',
    ],
    availableFrom: '2026-06-01',
    availableTo: '2026-06-14',
    rooms: [
      {
        id: 'h5-r1',
        roomType: 'Standard Single',
        description: 'Compact room ideal for solo travelers.',
        pricePerNight: 1800,
        maxOccupancy: 1,
        bedConfig: '1 Single Bed',
        imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80',
        amenities: ['AC', 'TV', 'Attached bathroom'],
        availableCount: 8,
      },
      {
        id: 'h5-r2',
        roomType: 'Standard Double',
        description: 'Simple double room for two guests.',
        pricePerNight: 2600,
        maxOccupancy: 2,
        bedConfig: '1 Double Bed',
        imageUrl: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80',
        amenities: ['AC', 'TV', 'Hot water'],
        availableCount: 5,
      },
    ],
  },
  h6: {
    id: 'h6',
    name: 'Mountain View Lodge',
    city: 'Shimla',
    address: 'The Ridge, Shimla 171001',
    starRating: 4,
    description:
      'A scenic mountain lodge offering breathtaking views of the Himalayas. Cozy interiors, warm hospitality, and easy access to Shimla’s top attractions.',
    amenities: [
      'Free Wi-Fi',
      'Mountain-view terrace',
      'Bonfire nights',
      'In-house restaurant',
      'Heating in all rooms',
      'Trekking assistance',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80',
    ],
    availableFrom: '2026-06-12',
    availableTo: '2026-06-30',
    rooms: [
      {
        id: 'h6-r1',
        roomType: 'Valley View Room',
        description: 'Comfortable room with stunning valley views.',
        pricePerNight: 4500,
        maxOccupancy: 2,
        bedConfig: '1 Queen Bed',
        imageUrl: 'https://images.unsplash.com/photo-1587985064135-0366536eab42?w=800&q=80',
        amenities: ['Valley view', 'Heating', 'Tea/Coffee maker'],
        availableCount: 3,
      },
      {
        id: 'h6-r2',
        roomType: 'Family Cottage',
        description: 'Two-bedroom cottage with living area and fireplace.',
        pricePerNight: 8200,
        maxOccupancy: 5,
        bedConfig: '2 Queen Beds',
        imageUrl: 'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=800&q=80',
        amenities: ['Fireplace', 'Living room', 'Private balcony'],
        availableCount: 1,
      },
    ],
  },
}
